### ISSUE TITLE
Gliederung anpassen

### ISSUE THREAD

**Issue by florianthiery** [Research-Squirrel-Engineers/DGUF_Leitfaden#2]

**Comment by SCSchmidt** [comment]
Den Gliederungsvorschlag hab ich nochmal ien klein bisschen geändert und dann auch schon angefangen umzusetzen. 
Hab leider vergessen, dass über einen Pull-Request zu tun, den man hier gut referenzieren könnte...  
schorry.

**Comment by bellerophons-pegasus** [comment]
Habe noch einmal ein wenig an der Gliederung geschraubt. 
Bin nämlich der Ansicht, dass zuerst FAIR, dann Open Science und dann CARE besprochen werden sollte. FAIR beinhaltet nämlich nicht die Forderung nach 'Open x' und ist so etwas wie ein Minimalstandard, während Open Sciene und CARE dann entsprechend noch mehr fordern. 
Werde auch noch weiter ausformulieren, wenn ich wieder beide Hände frei habe.

**Comment by bellerophons-pegasus** [comment]
Noch einmal etwas an der Gliederung gefeilt. 
@nevrome könntest du bitte noch einen Blick nach ganz unten bei den Kriterien werfen? Da habe ich den Abschnitt "Die handwerkliche Qualität" reinkopiert, der da irgendwo eingearbeitet gehört, da das für den ersten eher theoretischen Teil schon zu spezifisch ist.

**Comment by nevrome** [comment]
@bellerophons-pegasus Danke - Ich habe mir überlegt, wo es hingehören könnte.

**Comment by hpclutz** [comment]
Beim Überarbeiten von ein paar Rezensionskriterien ist mir ein starker Überlapp aufgefallen, wie z.B. Nutzbarkeit und Hilfedateien. Ich schlage vor, die Kriterien hierarchisch zu untergliedern in solche die einer Spezifikation ähneln und solche die eher subjektiver Natur sind - vgl. auch Issue #3

**Comment by archaeoklammt** [comment]
Ich schließe den Task, denn die generelle Gliederung steht nicht mehr so in der Diskussion, sondern der zweite Teil - die Ideen zur Vorgehensweise und den konkreten Kriterien. Hier sind fallen jeweils spezifische ToDos an, die als neue Issues laufen können.
