### ISSUE TITLE
Endredaktion: Check gendergerechte Sprache / männl. Schreibweise

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#20]
In Text und Kommentaren werden verschiedene Lösungen verfolgt - je nach dem, wer es geschrieben hat.

**Comment by SCSchmidt** [comment]
Ich bin für das Gender-Sternchen. Kann aber sein, dass die ArchInf uns das wieder rausstreichen. Die gendern nicht, wenn ich das recht sehe.
Für "unseren" draft und die homepage würde ich es drinnen lassen.

**Comment by bellerophons-pegasus** [comment]
Das sollten wir ganz zum Schluss bereinigen. 
Ich persönlich mag weder Stern noch Schrägstrich oder Binnen-I. Die stören mich immer im Lesefluss. 
Für einen Artikel habe ich mir mit Ersatzwörtern geholfen: https://geschicktgendern.de/ und an einigen wenigen stellen auch tatsächlich einfach beide Geschlechter aufgezählt ... aber mittlerweile ist das ja auch nicht mehr binär und eine Wissenschaft für sich geworden.

**Comment by archaeoklammt** [comment]
Habe gerade Druckfahne von DGUF erhlaten und @SCSchmidt hatte natürlich recht: DGUF setzt alles einheitlich auf "Nutzer" etc. Insofern können wir schauen, dass wir entlang von @bellerophons-pegasus Handreichung arbeiten.
Ich benenne den Task daher um und schiebe ihn wie vorgeschlagen zum Meilenstein "Endredaktion".
