### ISSUE TITLE
Abschnitt FAIR straffen und kürzen

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#21]
> [MT] Dieser Absatz sollte besser in den Anfang dieses Abschnittes eingearbeitet werden
> [MT] Insgesamt kann man das ganze aber auch weiter straffen; Wir wollen ja nicht nur die IT-Nerds, sondern auch die Archäologen mit dem Aufsatz erreichen. Da sollte es reichen knapp und einleuchtend die wichtigen Begriffe einzuführen und dann einfach auf entsprechende Literatur zu verweisen.

**Comment by archaeoklammt** [comment]
> [MT] Die Übersetzung aus dem Artikel ist etwas missglückt. 'Interoperability for research software can be understood in two dimensions: as part of workflows (horizontal dimension) and as stack of digital objects that need to work together at compilation and execution times (vertical dimension).'; Dass mit der 'Abfolge von Prozessen die bei der...' müsste umformuliert werden; Dann wird der Zusammenhang mit den Betriebssystemen auch wieder klar.
> [MT] lässt sich auch alles noch etwas straffen
> [AK] Gerne, bitte einfach machen.

**Comment by SCSchmidt** [comment]
hab da gerade ganz viel rumgebastelt.

**Comment by archaeoklammt** [comment]
Denke der task kann zu. Er sollte ja nur die Kommentare dazu konservieren. das ist jetzt "historisch"
