### ISSUE TITLE
Kommentare Abschnitt "handwerkliche Qualität"

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#23]
> [MT] dieser und die nächsten drei Abschnitte sind ja eigentlich schon etwas konkretere Kriterien. Müsste man etwas umbauen, denke ich

**Comment by bellerophons-pegasus** [comment]
Die Abschnitte wurden inzwischen an etwas passendere Stellen geschoben. Jedoch muss der Fließtext noch überarbeitet werden, um das abzurunden

**Comment by archaeoklammt** [comment]
Geschlossen (erfolgreich !), weil inzwischen Teil von Issue "Umstellen" und dann anschließend neuer Issue "Eindampfen".
