### ISSUE TITLE
Autorinnen und Autoren, Affilation anfügen, Titel eventuell streichen?

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#25]

**Comment by bellerophons-pegasus** [comment]
Beides gern

**Comment by florianthiery** [comment]
Ich brauch meinen Titel nicht, nur als Affil. werden die Squirrel stehen müssen, da ich meinen Arbeitgeber nicht verwenden darf

**Comment by florianthiery** [comment]
hab mal die Titel entfernt und sortiert, bei euch bitte die affiliation per PR hinzufügen

**Comment by SCSchmidt** [comment]
Wenn wir noch ein zwei Wochen warten, kann ich da vmtl "DAI" hinschreiben. ;-P

**Comment by archaeoklammt** [comment]
Très bien ! Félicitations !!

Dr. Anne Klammt
Digital Humanities
Humanités numériques

E-Mail: aklammt@dfk-paris.org<mailto:aklammt@dfk-paris.org>

Deutsches Forum für Kunstgeschichte Paris
Centre allemand d’histoire de l’art Paris
Hôtel Lully
45, rue des Petits Champs
F-75001 Paris

https://dfk-paris.org


De : Sophie C. Schmidt [mailto:notifications@github.com]
Envoyé : mercredi 24 juin 2020 12:56
À : Research-Squirrel-Engineers/DGUF_Leitfaden <DGUF_Leitfaden@noreply.github.com>
Cc : Klammt, Anne <aklammt@dfk-paris.org>; Assign <assign@noreply.github.com>
Objet : Re: [Research-Squirrel-Engineers/DGUF_Leitfaden] Autorinnen und Autoren, Affilation anfügen, Titel eventuell streichen? (#25)


Wenn wir noch ein zwei Wochen warten, kann ich da vmtl "DAI" hinschreiben. ;-P

**Comment by SCSchmidt** [comment]
Danke! :-D 
NFDI macht's möglich. Für 3 Monate.
