### ISSUE TITLE
Webseite abgeschossen?

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#26]
Holla, ich habe Text im Draft geändert, nun geht die Webseit enicht mehr. Ein Traum ....

**Comment by situx** [comment]
Was geht nicht mehr? Kann es gerade nicht nachvollziehen

**Comment by archaeoklammt** [comment]
Hi Timo,
sorry für diese Null-CheckerEmails.
Von hier https://research-squirrel-engineers.github.io/DGUF_Leitfaden/ passiert nüscht, wenn ich „Webseite“ klicke.

BG
Anne

Dr. Anne Klammt
Digital Humanities
Humanités numériques

E-Mail: aklammt@dfk-paris.org<mailto:aklammt@dfk-paris.org>

Deutsches Forum für Kunstgeschichte Paris
Centre allemand d’histoire de l’art Paris
Hôtel Lully
45, rue des Petits Champs
F-75001 Paris

https://dfk-paris.org


De : Timo [mailto:notifications@github.com]
Envoyé : mardi 23 juin 2020 14:42
À : Research-Squirrel-Engineers/DGUF_Leitfaden <DGUF_Leitfaden@noreply.github.com>
Cc : Klammt, Anne <aklammt@dfk-paris.org>; Author <author@noreply.github.com>
Objet : Re: [Research-Squirrel-Engineers/DGUF_Leitfaden] Webseite abgeschossen? (#26)


Was geht nicht mehr? Kann es gerade nicht nachvollziehen

**Comment by situx** [comment]
Da passiert auch nichts. Der Artikel ist ja unter dem Draft Link.
https://research-squirrel-engineers.github.io/DGUF_Leitfaden/Draft.html

**Comment by florianthiery** [comment]
Ist dann dann zum Schließen @archaeoklammt ?
