### ISSUE TITLE
Finale: Titel in deutscher und englischer Sprache

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#29]
"1. einen Titel in deutscher und englischer Sprache;"

http://www.dguf.de/ai-redaktionsrichtlinien.html

**Comment by archaeoklammt** [comment]
Es wäre prima, wenn wir den englischen Titel auch gleich bei der Veröffentlichung des Draft "testen lassen".

**Comment by SCSchmidt** [comment]
"Recommendations for the review of archaeological research software - what constitutes "good" research software"?
Oder wolltest du den Titel allgemin nochmal diskutieren?

> Es wäre prima, wenn wir den englischen Titel auch gleich bei der Veröffentlichung des Draft "testen lassen".
Du meinst schonmal mit anlegen und von Leuten kommentieren lassen?

**Comment by archaeoklammt** [comment]
Done und Danke
