### ISSUE TITLE
Kriterien zur Software-Evaluation

### ISSUE THREAD

**Issue by florianthiery** [Research-Squirrel-Engineers/DGUF_Leitfaden#3]
Tabelle zur schnellen Übersicht. Kriterien dürfen gern noch ergänzt oder angepasst werden.
Anleitung ist [unten](https://github.com/Research-Squirrel-Engineers/DGUF_Leitfaden/issues/3#issuecomment-648367218) zu finden.

| Kriterium                                     | Anne    | Sophie | Martina | Timo | Clemens | Lutz | Florian | Hubert |
|-----------------------------------------------|---------|--------|---------|------|---------|------|---------|--------|
| Wissenschaftliche Relevanz und Korrektheit    | &#9745; |     | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Einsatzgebiet                                 | &#9745; | &#9745; | &#9745; |      | &#9745; |     |  &#9745;  |        |
| Relevanz                                      |         |        | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Korrektheit der Implementierung               |         |&#9745; | &#9745; |      | &#9745; |     |  &#9745;  |        |
| Vergleichbarkeit der Implementierung          |         |        | &#9745; |      |         |      |         |        |
| Bedienbarkeit, Usability                      | &#9745;   |&#9745; | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Installation und Nutzungsumgebung             | &#9745;  |&#9745; | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Interface                                     |         |        | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Barrierefreiheit                              | &#9745; |&#9745; |         |      | &#9745; |      |  &#9734;  |        |
| Anschlussfähigkeit                            | &#9745;   |&#9745; | &#9745; |      | &#9745; |     |  &#9745;  |        |
| Input                                         | &#9745;  |&#9745; |         |      | &#9745; |     |  &#9745;  |        |
| Output                                        | &#9745;   |&#9745; |         |      | &#9745; |      |  &#9745;  |        |
| Zugänglichkeit, Hilfefunktionen und Community | &#9745;  |&#9745; | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Technik                                       |         |        |         |      | &#9745; |      |         |        |
| Qualität der Implementierung                  |         |        |         |      | &#9745; |      |  &#9745;  |        |
| Dokumentation und Tests                       |         |&#9745; | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Quellcodedokumentation                        |         |        | &#9745; |      | &#9745; |      |  &#9745;  |        |
| Buildprozess                                  |         |        |         |      | &#9745; |      |  &#9745;  |        |
| Entwicklerdokumentation                       |         |        |         |      | &#9745; |      |  &#9745;  |        |
| Sicherheit                                    |         |        |         |      |         |      |  &#9734;  |        |
| Sicherheitsanforderungen, Standards           | &#9745;|&#9745; |         |      | &#9745; |      |  &#9745;  |        |
| Sicherheitslücken                             | &#9745;|        | &#9745; |      |         |      |  &#9745;  |        |
| Rechtliche Fragen                             | &#9745;|        |         |      |         |      |         |        |
| Lizenzierung                                  | &#9745;|&#9745; | &#9745; |      | &#9745; |     |  &#9745;  |        |
| Open Source, Free and Open Source             | &#9745; |&#9745; | &#9745; |      | &#9745; |     |  &#9745;  |        |
| Rechtliche Implikationen                      |         |        |         |      |         |      |         |        |
| Datenschutz, Privacy, Datensparsamkeit        | &#9745; |&#9745; |         |      | &#9745; |      |  &#9745;  |        |

**Comment by bellerophons-pegasus** [comment]
In dem Entwurf sind bereits einige Vorschläge für Kriterien der Sofware-Evaluation. 
Siehe [hier](https://github.com/ennatmm/DGUF_Leitfaden/blob/master/Draft.md#kriterien-zur-beurteilung-von-software)

Um unnötige Arbeit zu vermeiden, kann hier jeder auflisten, was für relevant oder weniger relevant gehalten wird. Das kann dann verschnitten werden.

**Comment by SCSchmidt** [comment]
@bellerophons-pegasus , sorry der doofen Nachfrage, aber das System hab ich nicht ganz gerallt: Soll ich hier im Thread aufführen, was ich sinnvoll halte oder in den Draft reinschreiben?

**Comment by bellerophons-pegasus** [comment]
Hier im Thread. 
Habe mir auch was schlaues überlegt, das ich gleich im nächsten Kommentar einbaue.

**Comment by bellerophons-pegasus** [comment]
In der Beschreibung ist nun eine Tabelle zum 'ankreuzen' da. Man kann leider keine anklickbaren Checkboxen in Tabellen hier einfügen (in Listen geht das). Daher muss man den Quellcode bearbeiten. Entweder direkt hier, oder, wer eine visuelle Unterstützung braucht, kann auf https://www.tablesgenerator.com/markdown_tables# den gesamten Tabellencode in das obere Fenster reinkopieren und die Tabelle dann entsprechend anpassen. Dann auf 'generate' klicken und den neuen Code vom unteren Fenster wieder in die Beschreibung einfügen. 
Für die Box wird `&#9744;` und für die abgehakte Box `&#9745;` verwendet. Letzteres bedeutet 'finde ich relevant'.

**Comment by nevrome** [comment]
@bellerophons-pegasus Könntest du nochmal kurz ausführen, was es bedeutet, wenn ich ein Häckchen setze?

**Comment by bellerophons-pegasus** [comment]
Ah ja: ich hätte gedacht Häkchen bedeutet 'finde ich relevant'
Und wenn jemand mehr dazu ausführen möchte, gibt es hier in den Kommentaren ausreichend Platz

**Comment by florianthiery** [comment]
meine Haken sind drin, hab leider nur deinen "leeren haken" @bellerophons-pegasus rausgemacht den musste wieder reinsetzen, weiß nimmer wo :-( hab da nen leeres sternchen für sowas verwendet

**Comment by archaeoklammt** [comment]
Hola, die Tabelle finde ich prima. Ich gebe aber zu, dass es Punkte gab, bei denen ich nicht genau wusste, was es ist bzw. wie ich das von anderen Punkten abgrenze. Das betrifft insbesondere die Themen Sicherheit, Dokumentation/Builtprozesse und ein wenig auch rechtsfragen. Aber das ist ja vielleicht auch eine interessante Info..... :-$

**Comment by SCSchmidt** [comment]
Ich weiß gerade nicht genau, welcher Punkt exakt mit "Relevanz" gemeint war. War das der von Lutz? :-D 

Ein paar Punkte waren Überschriften, richtig? Hab sie... nicht angehakt, wenn ich die Unterpunkte angehakt hab oderso.

**Comment by bellerophons-pegasus** [comment]
Ja, da waren auch ein paar Überschriften dabei. Habe nämlich einfach mal die Kriterien kopiert und fast nur die Überschriften belassen... teilweise aber auch Stichworte aus den Listen verwendet. War da nicht ganz konsequent, aber fürs erste sollte das so reichen.
@florianthiery die leere Box ist nicht so wichtig; geht ja auch ohne

**Comment by bellerophons-pegasus** [comment]
Man kann übrigens einen Unterschied zwischen den eher archäologisch Arbeitenden und den eher informationstechnologisch Arbeitenden erkennen ;-)

**Comment by florianthiery** [comment]
Hahahaha

**Comment by archaeoklammt** [comment]
> Man kann übrigens einen Unterschied zwischen den eher archäologisch Arbeitenden und den eher informationstechnologisch Arbeitenden erkennen ;-)

Nein? Aber nie im Leben! ;)

**Comment by SCSchmidt** [comment]
> > Man kann übrigens einen Unterschied zwischen den eher archäologisch Arbeitenden und den eher informationstechnologisch Arbeitenden erkennen ;-)
> 
> Nein? Aber nie im Leben! ;)

Wenn @hpclutz, @situx und Hubert ihre Haken gesetzt haben, können wir das ja mal durch nen Cluster-Algorithmus schicken... :-D

**Comment by hpclutz** [comment]
Ok, sorry, die Liste ist viel zu umfangreich, um hilfreich zu sein. Viele der angeführten Punkte sind harte Spezifikationen, die zwar in einer Rezension angeführt werden können, aber eigentlich keine Beurteilung darstellen. Ich würde daher vorschlagen, in "harte" und "weiche" Kriterien zu unterteilen - damit meine ich nicht prio, sondern ob diese rein technisch sind (Lizenzen, Dateiformate) oder subjektiv relevant (Bedienbarkeit, Anwendungsspektrum). Alle "hart technischen" Kriterien sollten meines Erachtens in der Rezension nur angeführt werden, soweit bekannt (Mindest-Systemanforderung, unterstützte Dateiformate etc.)
Ergänze: ich würde das auch entsprechend im Text gliedern.

**Comment by archaeoklammt** [comment]
Liste wird jetzt einsortiert in Draft und Umfrage ist geschlossen.
