### ISSUE TITLE
Finale: Autorenliste inkl. ORCID /  eine Adresse / institutionelle Anbindung 

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#30]
"2. eine vollständige Liste der Autoren (siehe unten: Autorenschaft), möglichst inkl. deren ORCID; siehe DGUF-Handreichung zur ORCID [PDF];"
"8. eine Adresse / institutionelle Anbindung des Autors, soweit, wie sie veröffentlicht werden soll. "

http://www.dguf.de/ai-redaktionsrichtlinien.html

**Comment by situx** [comment]
Alle Autoren können am Anfang der Draft.md Datei ihre ORCID angeben und sie wird sofern vorhanden auch mit in den Titel übernommen.
Für einige Autoren habe ich die ORCIDs auch bereits herausgesucht. Bitte prüft ob ich dabei keinen Fehler gemacht habe.

**Comment by archaeoklammt** [comment]
Done und danke!
