### ISSUE TITLE
Finale: fünf Schlagwörter deutsch/englisch

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#31]
"5. eine Liste von mindestens fünf Schlagwörtern in deutscher und englischer Sprache; siehe DGUF-Handreichung zur Vergabe von Schlagwörtern (https://www.dguf.de/fileadmin/user_upload/publikationen/DGUF-Dok_Handreichung-fuer-Autoren_Schlagwoerter.pdf);"

**Comment by situx** [comment]
Schlagwörter können nun ebenfalls in der Draft.md unter den keywords und keywords_en keys hinzugefügt werden. Über den Stil können wir ggf. noch reden.

**Comment by archaeoklammt** [comment]
Super. Bei meinen beiden Rezensionen, die gerade über die DGUF rausgegangen sind, musste ich allerdings keine Schlagwörter vergeben. Anscheinend beziehen sich die Redaktionsrichtlinien auf Forschungsbeiträge. ABER man soll gerne für die Veröffentlichung des Preprint und dessen Bewerbung über Twitter und Facebook Hashtags vergeben. Dafür könnten wir unsere Keywords nutzen.

**Comment by archaeoklammt** [comment]
Geklärt beim Treffen am 17/09
