### ISSUE TITLE
Finale: Selbstvorstellung Autor*innen

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#32]
"7. am Ende eine kurze Selbstvorstellung des Autors/der Autoren ("Über den Autor")"

http://www.dguf.de/ai-redaktionsrichtlinien.html

**Comment by situx** [comment]
Ich habe für die Selbstvorstellungen der Autoren am Beginn der Draft.md pro Autor einen bio: Key erstellt. Ihr könnt bei mir für ein Beispiel schauen. 
Dort könnt ihr die Selbstvorstellung schreiben. 
Mir ist noch nicht klar wo die Selbstvorstellungen in der Publikation erscheinen sollen, aber wenn wir das wissen kann ich das Layout so anpassen, dass sie dort erscheinen.

**Comment by archaeoklammt** [comment]
Ich habe diese Selbstvorstellung aus den Redaktionsrichtlinien gezogen, aber selbst noch bei keiner Rezension in den Arch. Informationen verwendet. Entsprechend ist das wohl wenn nur bei den Forschungsbeiträgen in der Zeitschrift so und wir können diesen Punkt streichen. Daher habe ich den Task geschlossen. Danke Timo für die Arbeit!
