### ISSUE TITLE
zur Einreichung: Erklärung Anteile Autorenschaft

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#33]
"12. eine kurze Erklärung über die Anteile einzelner Autoren am Manuskript (siehe unten: Autorenschaft);"

"Autorenschaft und Darlegung von Finanzierung und Interessenkonflikten
Die Arch. Inf. begrüßen wissenschaftliche Kooperationen und von mehreren Autoren verfasste Beiträge. Werden Beiträge von mehreren Autoren verfasst, sollte sich die Reihenfolge der Autoren an den naturwissenschaftlichen Gepflogenheiten orientieren. Demnach werden die Autoren nicht in der alphabetischen Reihenfolge ihrer Namen genannt, sondern entsprechend ihres Anteils am vorgelegten Beitrag: Der Erstautor ist derjenige, der den Beitrag maßgeblich geschrieben hat und die Hauptverantwortung trägt; er ist bis auf begründete Ausnahmen (z. B. Sprachbarrieren) auch der korrespondierende Autor. Weitere Autoren werden in der Reihenfolge ihres Anteils am Beitrag genannt. Bei Forschungsgruppen fungiert der das Projekt überwachende Laborleiter, der Leiter der Forschungsgruppe oder der Antragsteller der Drittmittel in der Regel als letztgenannter Autor. Die Arch. Inf. regen an, im Falle einer Autorenkette am Ende eines Aufsatzes den konkreten Forschungsbeitrag der einzelnen Autoren explizit offen zu legen ("Beiträge der Autoren"/ "authors' contributions"). Hier kann z. B. dargelegt werden, wer die Gesamtverantwortung inne hat, wer welchen Teil der Datenerhebung vornahm und wer die statistische Auswertung durchführte.

Sofern inhaltlich sinnvoll, sollte am Ende eines Beitrags explizit die Finanzierung eines Aufsatzes oder Projekts offengelegt werden und auf die Interessen- und Rollenkonflikte bzw. die Befangenheit der Autoren hingewiesen werden. Wenn beispielsweise ein Autor, der eine neue hilfreiche Technik vorstellt, zugleich der Geschäftsführer der Herstellerfirma ist oder von selbiger bezahlt wird, muss den Lesern diese Information zugänglich gemacht werden. "

[(http://www.dguf.de/ai-redaktionsrichtlinien.html)]

**Comment by florianthiery** [comment]
das wird ne lustige Aufstellung ;-)

**Comment by SCSchmidt** [comment]
Würde sowas vorschlagen wie 
"Vorlage des Themas und Ausarbeitung eines ersten Entwurfs nach Diskussion mit den Co-Autoren: Anne Klammt, für alle weiteren Änderungen bitten wir diese unter https://github.com/Research-Squirrel-Engineers/DGUF_Leitfaden/pulse nachzulesen."

**Comment by SCSchmidt** [comment]
Ich mein. Wozu machen wir das denn alles online und open bitte. *eyeroll*

**Comment by SCSchmidt** [comment]
Oder is der hier besser: https://github.com/Research-Squirrel-Engineers/DGUF_Leitfaden/graphs/contributors ?

**Comment by florianthiery** [comment]
Oh ich muss schnell 200 commits machen dann komm ich nach vorn ;-) ich finde da ne alphabetische aufstellung die beste ganz ehrlich @SCSchmidt

**Comment by archaeoklammt** [comment]
Vorschlag: Frage aktuell zurückstellen und nach Veröffentlichung als Github-Page konkret bei Arch.-Informationen anfragen, wie es laufen könnte, wenn der Beitrag angenommen wird. Er wird ja auch dort durch einen Review gehen. Ansonsten finde ich auch, dass es bei uns nicht passt. Aber eigentlich ist es sehr schön, dass die DGUF darauf achtet, dass nicht automatisch Laborleitungen oder die Prof. Dr. Aachen vorne steht, obwohl vieleicht wirklich ein, zwei andere Personen die Arbeit gemacht haben - finde ich.

**Comment by SCSchmidt** [comment]
> Oh ich muss schnell 200 commits machen dann komm ich nach vorn ;-) ich finde da ne alphabetische aufstellung die beste ganz ehrlich @SCSchmidt

:-D  Dann mal los, @florianthiery ! go get your :1st_place_medal: 

Tja, Anzahl von commits ist kein perfektes Maß für Input. Aber hier ging es ja nicht nach Aufstellung der Autoren, sondern darum, dass der Einfluss der einzelnen Autoren auf den Text dargelegt werden soll. Und @archaeoklammt hat recht. Das ist eigentlich ein feature und kein bug. Guter Hinweis! 
Finde es aber doch auch schwierig. Wir könnten dann höchstens so etwas sagen wie "xy hat besonders Kap Z ausgearbeitet", aber am Ende hatten jetzt schon alle ihre Finger überall drin, oder?

**Comment by florianthiery** [comment]
Jups @SCSchmidt finde das generell für nen Fachbeitrag richtig nur sind wir hier kein klassischer Beitrag ;-)

**Comment by archaeoklammt** [comment]
Oui! C'est vrai.

**Comment by hpclutz** [comment]
Ganz ehrlich, bei der Anzahl Autoren spielt nur noch Erst- und Letztautor eine Rolle und detaillierte Aufschlüsselung ist imho nicht relevant ;)

**Comment by archaeoklammt** [comment]
Auch hier ist mir nach einigem Überlegen eingefallen, dass bei einer Rezension, die ich mit einem Kurs zusammen erstelt habe, nichts Vergelichbares von den Arch. Informationen gefordert wurde. Ich vermute also auch hier, dass die Redaktionsrichtlinien sich hier auf die Forschungsbeiträge in der Zeitschrift beziehen. Daher schließe ich diesen Task.
