### ISSUE TITLE
zur Einreichung: Festlegen korresp. Autorinnen

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#34]
"3. die Angabe des korrespondierenden Autors inkl. Name, Titel, Adresse oder institutioneller Anbindung und E-Mail-Adresse, bei zwei Autoren zusätzlich auch für den Zweitautor;"

http://www.dguf.de/ai-redaktionsrichtlinien.html

**Comment by SCSchmidt** [comment]
uh. müssen wir jetzt diskutieren, wer numero 2 is?

**Comment by archaeoklammt** [comment]
Vorschlag: Frage zurückstellen und in Redaktionssitzung besprechen, wenn wir wissen, ob der Beitrag zur Veröff. angenommen wird.

**Comment by archaeoklammt** [comment]
A.) Mal pragmatisch: Wer nimmt es auf sich, die Kommunikation zu führen und Fragen in die Gruppe zu tragen, verlässlich zu antworten usw.?
B.) Ich plädiere für ein nach Vorne treten, der Software-Entiwckler/innen unter uns

**Comment by archaeoklammt** [comment]
Geklärt beim Treffen am 17/09.
