### ISSUE TITLE
Zitation umwandeln nach APA-6 style s. cslDatei

### ISSUE THREAD

**Issue by archaeoklammt** [Research-Squirrel-Engineers/DGUF_Leitfaden#39]
Wie besprochen am 03/07/2020

**Comment by situx** [comment]
Ein Grossteil der Änderungen des Zitierungsstils ist bereits geschafft. Ich lese nochmal das APA6 Dokument der DGUF durch um auch wirklich alle Details beachtet zu haben.

**Comment by archaeoklammt** [comment]
Sind wir durch, oder?

**Comment by situx** [comment]
Da wir nun ja nicht dem Zitierstil 1:1 in der Webversion folgen wollen ja
