### ISSUE TITLE
minutes 19/06/20

### ISSUE THREAD

**Issue by florianthiery** [Research-Squirrel-Engineers/DGUF_Leitfaden#4]
hier gerne eure Notizen @SCSchmidt @archaeoklammt

**Comment by bellerophons-pegasus** [comment]
[Notizen](https://github.com/ennatmm/DGUF_Leitfaden/blob/master/2020-06-19_diskussion.md) von @SCSchmidt

**Comment by archaeoklammt** [comment]
Lieben Dank Sophie habe nur einen Punkt ergänzt.
