### ISSUE TITLE
Referenzen vereinheitlichen

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#47]
Mir ist aufgefallen, dass die Referenzen im Text nicht ganz einheitlich sind. Mal werden sie nur durch ein Komma voneinander getrennt, mal mit einem 'und' oder einem 'sowie'.

Außerdem gibt es mal einfach nur einen Link auf eine Webseite und manchmal dann eine im bibfile hinterlegte Referenz (auch nur mit einer Webseite). Dass sollte man zum Schluss auch noch einmal durchgehen.

**Comment by archaeoklammt** [comment]
Ein wenig schaut das @hpclutz beim Umwandeln an, @florianthiery ggfs. beim Grammatik Check mit einbeziehen.
