### ISSUE TITLE
Github Page follow up

### ISSUE THREAD

**Issue by ennatmm** [Research-Squirrel-Engineers/DGUF_Leitfaden#5]
Wollen wir an Plan einer Diskussion des Papers vor der Einreichung bei der DGUF/Arch. Infomrationen festhalten? 
Wenn ja, dann moittels Github-Page? 
Wer möchte sich dann darum kümmern?

**Comment by florianthiery** [comment]
Fände ich eine gute Sache @archaeoklammt , dann so wie du meintest als Git Pages ggf. mit einem Zenodo Link, dann können wir das da überarbeiten und über Pull Requests Änderungen reinholen und dann entwickelt sich das weiter. Ähnlich wie das bei dem [White Paper](https://github.com/opengeospatial/geosemantics-dwg) von dem @situx gesprochen hat, war, da hab ich dann genauso auch beigetragen.

**Comment by situx** [comment]
Ich kann das machen, aber ich darf es aktuell nicht. Denn dazu brauche ich erweiterte Rechte im Repository um die Github Page zu erstellen.

**Comment by bellerophons-pegasus** [comment]
Vielleicht kann man ja dann auch über die Arch. Informationen Werbung dafür machen. Und eventuell auch kurz erläutern wie Vorschläge und Änderungen eingereicht werden können.

**Comment by florianthiery** [comment]
@archaeoklammt @ennatmm bitte Timo / und / oder uns die Rechte dafür geben und @bellerophons-pegasus das wäre eine coole Sache, darüber auf jeden Fall verbreiten und ggf. noch über andere Kanäle.

**Comment by ennatmm** [comment]
Ich habe geschaut, aber ich finde nicht, wie ich die Rechte ändern könnte. Ich sehe nur collaborators.
Geändert habe ich jetzt, dass die GithubPages über den masterbranch abgewickelt werden. 
Hilft das? @situx

**Comment by florianthiery** [comment]
@ennatmm unter seetings > manage access > mitglied hinzufügen und Admin-Rechte geben :-)

**Comment by ennatmm** [comment]
> 
> 
> @ennatmm unter seetings > manage access > mitglied hinzufügen und Admin-Rechte geben :-)

Sollte man denken, ist aber nicht möglich. Ich habe keine Auswahlmöglichkeit, sondern kann nur collabs einladen. Ich kann die Rechte der Members nicht verändern. Alles das hätte ich von meinen wenigen Gitlab-Erfahrungen erwartet - jedoch ...
![add_collab](https://user-images.githubusercontent.com/40546882/85260284-b7b75580-b46a-11ea-8e89-c599d07d7651.PNG)

**Comment by florianthiery** [comment]
@ennatmm und ich haben das repo in https://github.com/Research-Squirrel-Engineers/DGUF_Leitfaden umgezogen und ihr solltet jetzt alle (vorrübergehend) Admin rechte haben, könnt also basteln wie ihr lustig seid.

**Comment by situx** [comment]
Wir haben nun eine Github Page.
Hauptseite:
https://research-squirrel-engineers.github.io/DGUF_Leitfaden/
Draft:
https://research-squirrel-engineers.github.io/DGUF_Leitfaden/Draft

Die Seite beinhaltet nun auch eine Bibliographie die aus dem BibTeX File gespeist wird. Alle Zitate von Literatur die ich im Text gefunden habe habe ich so angepasst, dass sie bei Klick auf ein Zitat zur Bibliographie scrollt.
Wenn ihr zitieren wollt geht bitte so vor:
1. Eintrag in die Bibtexdatei
2. Zitat mit Bibtex Key in Markdown: [@Bibtexkey p. 1-2](#BIBTEXKEY_IN_LOWERCASE)
Der Bibtexkey wird von bibtex.js automatisch als Anker im HTML Dokument angelegt, sodass darauf auch einfach mit einem Ankerlink verwiesen werden kann.

Das Design ist bisher ein Plain Bootstrap Design welches man bestimmt noch verbessern kann.

**Comment by archaeoklammt** [comment]
Können wir nicht ermöglichen, dass Änderungen auch direkt als Issues angelegt werden können, von den Leserinnen und Lesern ?

**Comment by situx** [comment]
Ich denke mal Issues kann jeder anlegen der einen Github Account hat, genauso wie Pull Requests.

**Comment by archaeoklammt** [comment]
Geklärt beim Treffen am 17/09
