### ISSUE TITLE
Änderung von DGUF_Leitfaden zu DGUF_AspekteSoftwareRezension?

### ISSUE THREAD

**Issue by florianthiery** [Research-Squirrel-Engineers/DGUF_Leitfaden#52]
Wir sollten den Namen des Repos dann auch ändern, wenn wir sonst überall das Wort Leitfaden raushaben wollen.

Änderung von DGUF_Leitfaden zu DGUF_AspekteSoftwareRezension?

**Comment by SCSchmidt** [comment]
dafür. Wir benutzen "Impuls" im Text, das find ich ganz gut.

**Comment by florianthiery** [comment]
also DGUF_AspekteSoftwareRezensionImpuls?

**Comment by SCSchmidt** [comment]
eher "Impuls_SoftwareRezensionen_DGUF" ...

**Comment by florianthiery** [comment]
> eher "Impuls_SoftwareRezensionen_DGUF" ...

find ich gut

**Comment by bellerophons-pegasus** [comment]
kann man so machen
