### ISSUE TITLE
Abschnitt 'Vorgehensweise' als Anleitung ausarbeiten

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#56]
Für den 'Normalrezensenten' könnte unsere Handreichung eine Keule sein, die eher zur Verwirrung beiträgt als dabei hilft eine Rezension von Forschungssoftware zu erstellen.

Die Gutachter dazu:
> Einerseits ist er durch eine grosse Breite der dargelegten Punkte recht lang, und zudem dadurch auch sehr detailliert und geht teilweise sehr in den technischen Bereich. Dadurch könnten aus meiner Sicht potentielle Rezensent*innen aus dem Bereich der ‚normalen‘ Nutzer*innen abgeschreckt werden, ihre Meinung einzubringen.

> In seiner aktuellen Form liest es sich zum Teil eher wie eine Handreichung zur Erstellung wissenschaftlicher Software, als eine zur Beurteilung eben dieser.

> deutlich zu machen, welches eben die essentiellen, welches wünschenswerte, und was optionale Aspekte sind, die eine Rezension umfassen sollte.

**Comment by bellerophons-pegasus** [comment]
Ein Vorschlag von @situx dazu:
Wäre vielleicht eine Grafik oder ein Entscheidungsbaum hilfreich?
Sowas wie: Was ist mein Background und welche Aspekte sollten hier
besonders wichtig sein? Ich denke das kam raus, dass man sich eine Art
"Leitfaden für den Leitfaden" wünscht weil die vielen Kriterien die wir
aufgeworfen haben doch vll etwas erschlagend wirken.

**Comment by archaeoklammt** [comment]
Stimme zu, dass die Kritik berechtigt ist und man das aufnehmen sollte. Die Idee eines Entscheidnungsbaums finde ich fortführend, aber denke, wir sollten ihn implizit in den Text einarbeiten. Unter anderem, weil diese Entscheidungsbäume meiner Meinung nach dann doch wieder auf Stereotypen, wie die der "normale" Leserin bzw. des "normalen" Lesers hinauslaufen und diese fortschreiben. Weiterhin finde ich es auch wichtig, dass ein Ergebnis der Lektüre des Impuls zu einer Handreichung sein kann, sich selbst als nicht hinreichend qualifiziert für das Anfertigen einer bestimmten Softwarerezension zu empfinden. Eventuell sollten wir deutlicher machen, dass Rezensionen möglicherweise wesentlich häufiger Teamarbeiten sein werden.

**Comment by bellerophons-pegasus** [comment]
Das wäre mein Vorschlag, mit Bitte um Feedback:

> Die Rezension archäologischer Forschungssoftware setzt die Sichtung von Dokumentation und Publikationen ebenso voraus, wie die praktische Erprobung der Software selbst. Unserem Verständnis nach sollte eine Softwarerezension, so wie es eine herkömmliche Besprechung einer wissenschaftlichen Publikation leistet, die Software zunächst mit zusammenfassenden Eckdaten vorstellen. Anschließend sollte der Kontext erläutert werden und eine kritische Beurteilung erfolgen.

> Zu den Eckdaten, welche tabellarisch dargestellt werden können, gehören unter anderem Angaben zur Version, zu den Entwicklern und der Lizenz. Dies ermöglicht z. B. eine schnelle Übersicht darüber, ob die begutachtete Software mit der eigenen technischen Umgebung kompatibel ist. Ein Vorschlag zu den Inhalten einer solchen Tabelle befindet sich am Ende dieses Beitrags.

> Mit Kontext ist eine Einordnung in das archäologische Forschungsfeld und Angaben zum möglichen Zusammenhang mit Forschungsprojekten, Arbeitsgruppen oder Institutionen gemeint. Auch der "Kontext" der rezensierenden Person sollte dargestellt werden, denn eine realistische und transparente Einschätzung der eigenen Kompetenzen und des eigenen Nutzungsinteresses stellt einen wichtigen Anhaltspunkt für die heterogene Leserschaft dar. Wurde die Rezension rein aus Sicht eines Anwenders oder auch aus Entwicklersicht geschrieben? Angaben zur verwendeten Testumgebung, also des zum Testen der Software genutzten Computers, können ebenfalls von Bedeutung sein, wie z. B. Angaben zu Betriebssystem, RAM, Prozessor, Grafikkarte oder Bandbreite.

> Für die kritische Beurteilung von Forschungssoftware aus verschiedenen Blickwinkeln folgt hier im Anschluss ein in drei Bereiche gegliederter Fragenkatalog. Die Fragen aus dem Bereich "Einsatz in der Archäologie und wissenschaftlicher Zweck" sollten unserer Ansicht nach in jeder Rezension behandelt werden. Als sehr wichtig erachten wir die Beantwortung der Fragen zu Installation, Tutorials, und der tragenden Community, sowie zu Ein- und Ausgabeformaten, Programmierschnittstellen und den Möglichkeiten zur Beteiligung an der Weiterentwicklung der Software.

> Allein diese Fragen ziehen weitere nicht unwichtige Folgefragen nach sich. Für die Installation wichtig sind Informationen dazu ob es sich um eine eigenständige (stand-alone) Software oder um eine Webanwendung handelt, ob die Installationsvoraussetzungen klar dokumentiert sind und ob die Dokumentation vollständig und aktuell ist relevant. Im Hinblick auf Tutorials und der tragenden Community stellen sich die Fragen ob eine archäologische Nutzung vorgesehen war, ob es publizierte Anwendungsfälle der Software gibt, ob an der Software aktiv gearbeitet wird und ob Testdatensätze zur Verfügung gestellt werden. Wenn es um Ein- und Ausgabeformate geht, sollte auch gefragt werden wie Daten generell eingelesen werden können. Auch die Bewertung der Bedienungsoberfläche und der Bedienungsmöglichkeiten, sowie die Robustheit der Software sollte unserer Meinung nach nicht fehlen.

> Die Ergebnisse der Begutachtung sollten in einer Stellungnahme zusammengefasst werden, welche die Software hinsichtlich ihrer Nützlichkeit, ihrer Bedienbarkeit, ihrer handwerklichen Qualität und ihrer Position in Relation zu den bereits Angesprochenen Idealen guter Forschungssoftware beurteilt.

> Der im Anschluss vorgestellte Fragenkatalog ist umfangreich. Somit wird zum Einen aufgezeigt, dass die Entwicklung von Forschungssoftware durchaus als wissenschaftliche Leistung gewertet werden kann. Zum Anderen dient er als Anstoß dazu die eigenen Kompetenzen für die Rezension von Forschungssoftware zu überdenken und die Evaluierung gegebenenfalls in einem Team durchzuführen. Denn so wie Rezensionen von herkömmlichen Publikationen im Idealfall von mit dem Thema betrauten Experten erstellt werden, sollte dies auch für Forschungssoftwarerezensionen gelten.

**Comment by florianthiery** [comment]
ich find den Teil sehr gut @bellerophons-pegasus :-)

**Comment by archaeoklammt** [comment]
Liebe Martina,
Ich finde es sehr gut !!

Beste Grüße
Anne

**Comment by situx** [comment]
Ich finde den Text auch gut, frage mich aber ob deutlich genug herauskommt, dass die Fragenkataloge als Angebot an die Reviewer verstanden werden diese je nach ihrem Wissensstand zu verwenden.
Ich glaube aktuell klingt es noch so als würden wir verschiedene Dinge verschieden gewichten, aber es könnte so verstanden werden, dass ein Reviewer diese trotzdem bearbeiten soll oder sich für die Review ein Team suchen soll.
Korrigiert mich wenn ich falsch liege.

**Comment by archaeoklammt** [comment]
Stimmt vielleicht, am besten konkreten Textvorschlag als Alternative anbieten. Das geht am leichtesten zu verarbeiten.

________________________________

Deutsches Forum für Kunstgeschichte Paris

Centre allemand d’histoire de l’art Paris

Hôtel Lully

45, rue des Petits Champs

F-75001 Paris


https://dfk-paris.org

________________________________

**Comment by nevrome** [comment]
Ich finde Martinas Text super. Vielleicht könnte man die Priorisierung im Katalog durch eine kleine Markierung hervorheben. z.B. könnte man jedem von uns als essentiell beschiedenen Punkt ein "⚠" oder etwas ähnliches voranstellen. In Lehrbüchern sind solche visuellen Hilfen ja sehr verbreitet. z.B.:

> ⚠ **Welche Datenformate werden wie eingelesen?** Sind alle relevanten Datenformate für die Aufgabe, die die Software im typischen Anwendungsfall lösen soll, einlesbar? Werden offene Datenformate unterstützt? Können Datenformate auch von gängigen Repositorien eingelesen werden (z. B. Webservices, Git, Cloud Services)?

Dann würde ich in dem Text oben nach 

> Als sehr wichtig erachten wir die Beantwortung der Fragen zu Installation, Tutorials, und der tragenden Community, sowie zu Ein- und Ausgabeformaten, Programmierschnittstellen und den Möglichkeiten zur Beteiligung an der Weiterentwicklung der Software. 

noch folgendes einfügen: 

> Diese Punkte sind im Katalogteil mit einem vorangestellten "⚠" markiert.

**Comment by bellerophons-pegasus** [comment]
Wir könnten sogar etwas abstufen: :bangbang: und :heavy_exclamation_mark:

**Comment by bellerophons-pegasus** [comment]
Neuer Enwurf. Etwas kürzer.

> Die Rezension archäologischer Forschungssoftware setzt die Sichtung von Dokumentation und Publikationen ebenso voraus, wie die praktische Erprobung der Software selbst. Unserem Verständnis nach sollte eine Softwarerezension, so wie es eine herkömmliche Besprechung einer wissenschaftlichen Publikation leistet, die Software zunächst mit zusammenfassenden Eckdaten vorstellen. Anschließend sollte der Kontext erläutert werden und eine kritische Beurteilung erfolgen.

> Zu den Eckdaten, welche tabellarisch dargestellt werden können, gehören unter anderem Angaben zur Version, zu den Entwicklern und der Lizenz. Dies ermöglicht z. B. eine schnelle Übersicht darüber, ob die begutachtete Software mit der eigenen technischen Umgebung kompatibel ist. Ein Vorschlag zu den Inhalten einer solchen Tabelle befindet sich am Ende dieses Beitrags.

> Mit Kontext ist eine Einordnung in das archäologische Forschungsfeld und Angaben zum möglichen Zusammenhang mit Forschungsprojekten, Arbeitsgruppen oder Institutionen gemeint. Auch der "Kontext" der rezensierenden Person sollte dargestellt werden, denn eine realistische und transparente Einschätzung der eigenen Kompetenzen und des eigenen Nutzungsinteresses stellt einen wichtigen Anhaltspunkt für die heterogene Leserschaft dar. Wurde die Rezension rein aus Sicht eines Anwenders oder auch aus Entwicklersicht geschrieben? Angaben zur verwendeten Testumgebung, also des zum Testen der Software genutzten Computers, können ebenfalls von Bedeutung sein, wie z. B. Angaben zu Betriebssystem, RAM, Prozessor, Grafikkarte oder Bandbreite.

> Für die kritische Beurteilung von Forschungssoftware aus verschiedenen Blickwinkeln folgt hier im Anschluss ein in drei Bereiche gegliederter Fragenkatalog. Die Fragen aus dem Bereich "Einsatz in der Archäologie und wissenschaftlicher Zweck" sollten unserer Ansicht nach in jeder Rezension behandelt werden. Als sehr wichtig erachten wir die Beantwortung der Fragen zu Installation, Tutorials, und der tragenden Community, sowie zu Ein- und Ausgabeformaten, Programmierschnittstellen und den Möglichkeiten zur Beteiligung an der Weiterentwicklung der Software. Allein diese Fragen ziehen weitere nicht unwichtige Folgefragen nach sich. Beispielsweise sind für die Installation auch Informationen dazu ob es sich um eine eigenständige (stand-alone) Software oder um eine Webanwendung handelt, ob die Installationsvoraussetzungen klar dokumentiert sind und ob die Dokumentation vollständig und aktuell ist, wichtig. Die unserer Ansicht nach besonders relevanten Fragen sind im Katalog mit einem vorangestellten :bangbang: (sehr wichtig) und :heavy_exclamation_mark: (wichtig) gekennzeichnet.

> Die Ergebnisse der Begutachtung sollten in einer Stellungnahme zusammengefasst werden, welche die Software hinsichtlich ihrer Nützlichkeit, ihrer Bedienbarkeit, ihrer handwerklichen Qualität und ihrer Position in Relation zu den bereits Angesprochenen Idealen guter Forschungssoftware beurteilt.

> Der im Anschluss vorgestellte Fragenkatalog ist umfangreich und muss auch nicht in allen Einzelheiten abgearbeitet werden. Er zeigt jedoch zum Einen auf, dass die Entwicklung von Forschungssoftware durchaus als wissenschaftliche Leistung gewertet werden kann. Zum Anderen dient er als Anstoß dazu die eigenen Kompetenzen für die Rezension von Forschungssoftware zu überdenken und die Evaluierung gegebenenfalls in einem Team durchzuführen. Denn so wie Rezensionen von herkömmlichen Publikationen im Idealfall von mit dem Thema betrauten Experten erstellt werden, sollte dies auch für Forschungssoftwarerezensionen gelten.

Als Beispiel für die Folgefragen habe ich das Thema 'Installation' genommen, da es an erster Stelle stand. Wenn ihr aber eines der anderen Themen aus dem dann entfernten Absatz (unten zur Referenz reinkopiert) lieber haben wollt, bitte melden. Ich würde aber sagen, dass ein Beispiel reicht, da wir ja sowieso den Fragenkatalog haben.

> Allein diese Fragen ziehen weitere nicht unwichtige Folgefragen nach sich. Für die Installation wichtig sind Informationen dazu ob es sich um eine eigenständige (stand-alone) Software oder um eine Webanwendung handelt, ob die Installationsvoraussetzungen klar dokumentiert sind und ob die Dokumentation vollständig und aktuell ist relevant. Im Hinblick auf Tutorials und der tragenden Community stellen sich die Fragen ob eine archäologische Nutzung vorgesehen war, ob es publizierte Anwendungsfälle der Software gibt, ob an der Software aktiv gearbeitet wird und ob Testdatensätze zur Verfügung gestellt werden. Wenn es um Ein- und Ausgabeformate geht, sollte auch gefragt werden wie Daten generell eingelesen werden können. Auch die Bewertung der Bedienungsoberfläche und der Bedienungsmöglichkeiten, sowie die Robustheit der Software sollte unserer Meinung nach nicht fehlen.

**Comment by nevrome** [comment]
Gefällt mir. Nur ein kleiner, sprachlicher Änderungswunsch: 

Statt

> Er zeigt jedoch zum Einen auf, dass die Entwicklung von Forschungssoftware durchaus als wissenschaftliche Leistung gewertet werden kann. Zum Anderen dient er als Anstoß dazu die eigenen Kompetenzen für die Rezension von Forschungssoftware zu überdenken und die Evaluierung gegebenenfalls in einem Team durchzuführen.

lieber

> Seine Komplexität und Tiefe ist ein guter Indikator dafür, dass die Entwicklung von Forschungssoftware eine vollwertige, wissenschaftliche Tätigkeit sein kann. Wir raten die eigenen Kompetenzen für die Rezension kritisch zu reflektieren und die Evaluierung gegebenenfalls in einem Team durchzuführen.

**Comment by archaeoklammt** [comment]
1A

________________________________

Deutsches Forum für Kunstgeschichte Paris

Centre allemand d’histoire de l’art Paris

Hôtel Lully

45, rue des Petits Champs

F-75001 Paris


https://dfk-paris.org

________________________________

**Comment by SCSchmidt** [comment]
Super!

**Comment by bellerophons-pegasus** [comment]
gelöst und gepusht
