### ISSUE TITLE
Überschriftenhierarchie prüfen

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#58]
> Mir ist nicht klar, ob die Überschriftenhierarchie stringent eingehalten wird. Vielleicht lohnt es sich, dies nochmals zu überprüfen?

**Comment by bellerophons-pegasus** [comment]
Das ist die Hierarchie (Nummern bei den Fragen einfach ignorieren, habe recycled). Hinter der Überschrift steht in Klammern jeweils die Ebene.

## Zielsetzung des Beitrags (2)

## Forschungssoftware (2)

### Forschungssoftware als wissenschaftliche Leistung (3)

### Gute Forschungssoftware (3)

#### FAIR-Prinzipien (4)

##### Findable (Auffindbar) (5)

##### Accessible (Zugänglich) (5)

##### Interoperable (Interoperabel) (5)

##### Reusable (Nachnutzbar) (5)

#### Open Science (4)

#### CARE-Prinzipien und Ethos (4)

## Mögliche Vorgehensweise zur Rezension archäologischer Forschungssoftware (2)

## Fragenkatalog zur Beurteilung von Software (2)
### Einsatz in der Archäologie und wissenschaftlicher Zweck (3)

* 1 Welche Aufgabenstellung versucht die Software zu lösen?
* 2 Wie löst die Software eine gegebene (technische) Aufgabe?
* 3 Wie funktioniert der wissenschaftliche Arbeitsablauf, der in der Software implementiert wurde?
* 4 Ist die Behauptung, eine bestimmte wissenschaftliche Fragestellung mit dem gewählten Arbeitsablauf beantworten zu können, korrekt?
* 5 Sind die Algorithmen korrekt implementiert worden?
* 6 Gibt es für die Archäologie relevante Projekte/Anwendungen, in der die rezensierte Software bereits angewendet wurde?
* 7 In welcher Form ist die Software publiziert?

### Bedienbarkeit und Zielgruppenorientierung  (3)
#### Installation (4)
* 8 Wie funktioniert die Installation und wo wird die Software vorgehalten?
* 9 Handelt es sich um eine eigenständige (stand-alone) Software oder um eine Webanwendung?
* 10 Sind grundlegende Voraussetzungen in Form von Hardware und Betriebssystem klar dokumentiert?

#### Interface (4)
* 11 Passt das User Interface zum Nutzerkreis?
* 12 Ist die archäologische Nutzung vorgesehen?
* 13 Orientiert sich die Menüführung an bestimmten Vorbildern?
* 14 Ist das Programm mehrsprachig bzw. in welchen Sprachen wird es angeboten?
* 15 Sind die Fehlermeldungen für die Rezensenten gut verständlich?

#### Performanz und Robustheit (4)
* 16 Ist die Implementierung performant?
* 17 Ist die Software robust?

#### Hilfefunktionen, Tutorials und Community (4)
* 18 Gibt es ausreichend Tutorials für das Erlernen der Software?
* 19 Gibt es für die Software Testdatensätze?
* 20 Sind weitere Informationen zur Software leicht zu finden?
* 21 Wird die Software von einer Community getragen? Ist diese möglicherweise ganz oder teilweise altertumswissenschaftlich geprägt?
* 22 Gibt es archäologische Best Practices oder Publikationen, die auf die rezensierte Software verweisen?

#### Dateningest, Interoperabilität und Schnittstellen (4)
* 23 Welche Datenformate werden wie eingelesen?
* 24 Welche Datenformate werden ausgegeben?
* 25 Wie können Daten eingelesen werden? Als Stapel oder nur einzeln? Ermöglicht die Software eine Stapelverarbeitung?
* 26 Gibt es eine Programmierschnittstelle (API)?

#### Konformität mit Regelungen zum Datenschutz und der Datensparsamkeit (4)
* 27 Werden die Gesetze (z. B. zu Datenschutz, Kartendarstellungen etc.) des Einsatzlandes durch die Software eingehalten?
* 28 Welche Daten speichert die Anwendung zu welchem Zweck und wie lange? Werden Daten an Dritte übertragen?

### Entwickler-Perspektive (3)
#### Dokumentation und Tests (4)

* 29 Ist eine Quellcodedokumentation vorhanden und ggf. eine HTML-Variante davon verfügbar?
* 30 Ist der Build-Prozess dokumentiert und ggf. mittels Buildingscripts automatisiert?
* 31 Ist die Dokumentation aktuell und adressiert sie alle Funktionen des Programms?
* 32 Gibt es eine Entwicklerdokumentation, welche eine evtl. Softwareerweiterung fördert?
* 33 Enthält der Quellcode Softwaretests, um die Kernfunktionen zu testen und diese für andere Entwickler aufzuzeigen?
* 34 Wird es dem Entwickler einfach gemacht, die Software zu testen (z. B. Virtuelle Maschine, Dockercontainer, Installer)?
* 35 Sind die Entwickler gut erreichbar?
* 36 Wird an der Software aktiv gearbeitet?
* 37 Ist es möglich, die Softwareentwicklung zu unterstützen?

#### Qualität der Implementierung (4)

* 38 Entspricht die Implementierung dem Stand der Technik?
* 39 Wird *Continuous Integration* zur Absicherung der Implementierungsqualität verwendet?

## Software-Eckdatentabelle (2)

## Ausblick (2)

## Anmerkungen (2)

## Bibliographie (2)

**Comment by nevrome** [comment]
Ich sehe hier kein offensichtliches Problem. 

**Mögliche Vorgehensweise zur Rezension archäologischer Forschungssoftware** ist sehr kurz für seinen Lvl. 2 Status, aber alternativen Setups -- wie z.B. alle Abschnitte ab diesem ein Lvl. abzustufen -- scheinen mir auch nicht besser. Ich denke, wir könnten diesen Kommentar einfach ignorieren oder bestätigen, dass die Überschriftenreihenfolge unser Ansicht nach stimmt.

**Comment by bellerophons-pegasus** [comment]
Ja, ich hatte auch den Eindruck, dass das passt. Werde noch mal in dem docx-Dokumen nachprüfen, ob da vielleicht was verrutscht war. Aber denke, das passt alle so.
