### ISSUE TITLE
Ausblick - streichen oder überarbeiten?

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#59]
Aktuell wirkt der Ausblick auf mich etwas 'hinten dran geklatscht'. Eventuell kann man den auch streichen und die relevanten Passagen daraus auch in die Einleitung oder die Einleitung für den Fragenkatalog übernehmen?

**Comment by bellerophons-pegasus** [comment]
Neue Überschrift: "Wie geht es weiter?"

* Diskussionsbeitrag
* Unsere Sicht der Dinge, nun bitte eure Stellungnahme

**Comment by bellerophons-pegasus** [comment]
Die anderen Inhalte vorne in Zielsetzung einarbeiten bzw. streichen, da teilweise schon vorhanden.

**Comment by bellerophons-pegasus** [comment]
Kurz und knackig?

> ## Wie geht es weiter?

> Die Diskussion über die Bewertung von Software in der Archäologie und ihren Nachbardisziplinen wurde gerade erst begonnen. Ein Konsens wurde noch nicht gefunden. Unsere hier vorgestellten Überlegungen und der Fragenkatalog sollen konkret als Impuls zur Etablierung eines Konsens verstanden werden. Wie anfangs angemerkt, sind Stellungnahmen erwünscht.

Kann man aber ganz sicher noch eleganter formulieren.

**Comment by nevrome** [comment]
Wenn es wirklich nur darauf hinauslaufen würde, dann würde ich auf diesen kleinen Annex verzichten. In der Sache steht das alles schon in der Einleitung.

**Comment by florianthiery** [comment]
Bei mir siehe PR #61 ich fände es gut so als Klammer im Text dass es nicht mit QGIS irgendwie aufhört. Aber ist meine persönliche Meinung ;-)
