### ISSUE TITLE
Frage zu Issue-assignement

### ISSUE THREAD

**Issue by ennatmm** [Research-Squirrel-Engineers/DGUF_Leitfaden#6]
Kurze Frage zur Vorgehensweise:
Weise ich Issue der Person zu, von der ich denke, sie könnte es vielleicht machen?
Wenn ja, dann müsste "Timo-Relevanz" allen außer Timo zugewiesen werden, oder?

**Comment by florianthiery** [comment]
können wir so machen, also assignees sind die, die die Aufgabe zugewiesen bekommen.
