### ISSUE TITLE
Frage in der Frage

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#64]
Gerade habe ich noch was entdeckt, das nochmal etwas Zuwendung braucht, da es eine Frage ist, in der noch eine Frage vorkommt:

* :heavy_exclamation_mark:**Handelt es sich um eine eigenständige (stand-alone) Software oder um eine Webanwendung?** Nicht jede Software muss lokal installiert werden, um genutzt werden zu können. Webanwendungen, die entweder dynamisch im Browser oder auf einem Server ausgeführt werden, sind heute zu beliebig komplexen Operationen in der Lage. Passt die Lösung der Plattform zum archäologischen Einsatz? Webanwendungen können beispielsweise nicht hinreichend performant sein, da sie den Transfer großer Datenmengen über das Internet erfordern. Sie sind im Gelände gegebenenfalls nicht ausführbar und daher nicht für alle Arbeitsbedingungen sinnvoll.

Auftrennen?
Umformulieren?

**Comment by nevrome** [comment]
Ich glaube weder noch. Die innere Frage bezieht sich ja auf die Rahmenfrage: *Stand-alone client oder Webapp und ist die gewählte Lösung sinnvoll?* - Das gehört zusammen. Tatsächlich gibt die zweite Frage der ersten erst wirklich Sinn.

**Comment by florianthiery** [comment]
eher

Nicht jede Software muss lokal installiert werden, um genutzt werden zu können. Webanwendungen, die entweder dynamisch im Browser oder auf einem Server ausgeführt werden, sind heute zu beliebig komplexen Operationen in der Lage. _Daher stellt sich die Frage, ob die Anwendung eher als lokale Installation oder als Webanwendung zum Einsatz in der archäologischen Praxis taugt._ Webanwendungen können beispielsweise nicht hinreichend performant sein, da sie den Transfer großer Datenmengen über das Internet erfordern. Sie sind im Gelände gegebenenfalls nicht ausführbar und daher nicht für alle Arbeitsbedingungen sinnvoll.

**Comment by florianthiery** [comment]
hab die Frage mal in Text umformuliert (kursiv) der glaube ich in der Frage enthalten ist, oder @bellerophons-pegasus @nevrome ?

**Comment by florianthiery** [comment]
siehe #65

**Comment by archaeoklammt** [comment]
@florianthiery genau so war es gemeint, wie es jetzt umformuliert ist.
