### ISSUE TITLE
Für Twitter in 250 Zeichen unser 'Elevator Pitch'

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#66]
Der Beitrag wird von der DGUF auf Twitter angekündigt und dafür ist eine 250-Zeichen lange Beschreibung nützlich.

Ein erster Aufschlag (mit 287 etwas zu lang):

Die Erstellung von Forschungssoftware stellt eine eigene wissenschaftliche Leistung in der Archäologie dar, welche durch geeignete Rezensionen sichtbar wird. Wir bieten einen Diskussionsimpuls zur Etablierung eines gemeinsamen Verständnisses der Anforderungen an solch eine Rezension.

**Comment by HubertMara** [comment]
179 Zeichen: Diskussionsimpuls für faire Rezensionen, Sichtbarmachung und Etablierung eines gemeinsamen Verständnisses für Forschungssoftware als wissenschaftliche Leistung in der Archäologie.

**Comment by archaeoklammt** [comment]
#RSE #Archäologie #review

**Comment by archaeoklammt** [comment]
Forschungssoftware greift tief in archäologische Forschung ein, umso wichtiger, dass nun Rezensionen die Software selbst in den Blick nehmen. Aber welche Kriterien sollte eine angemessene Besprechung beachten? Ein Diskussionsimpuls

**Comment by bellerophons-pegasus** [comment]
Mein Versuch alle drei Vorschläge in eines zu packen, inklusive Synonymgetrickse (248 Zeichen):

Da Forschungssoftware tief in archäologische Forschung eingreift, ist ihre faire Rezension wichtig. Ein Diskussionsimpuls zu Bewertungskriterien und der Bildung eines Konsens für Forschungssoftware als wissenschaftliche Leistung in der Archäologie.
