### ISSUE TITLE
Für Twitter und FB

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#67]
Die DGUF wird den Beitrag auf Twitter und Facebook bewerben. 
Dazu wären dann entsprechende Profile (FB & Twitter), Institutions-Handles (Twitter) und in absteigender Wichtigkeit Hashtags (Twitter) notwendig.

(Wer das hier nicht alles aufschreiben mag, kann mir das auch per E-Mail schicken)

**Comment by HubertMara** [comment]
Twitter: @_mainzed @i3mainz
Facebook ist weniger genutzt, daher nur der FB Technik: https://www.facebook.com/technik.hsmainz

**Comment by archaeoklammt** [comment]
Twitter: @DFKParis
Facebook: @DFKParis
instagram: @dfkparis
Twitter: @archaeoklammt

**Comment by nevrome** [comment]
Twitter: @nevromeCS + @MPI_SHH

**Comment by HubertMara** [comment]
Wenn auch die persönlichen Accounts gelistet werden sollen, dann bitte auch meinen Twitteraccount: @HubertMara

**Comment by florianthiery** [comment]
Twitter: @fthierygeo und @RSESquirrel
