### ISSUE TITLE
Acknowledgements für EN text

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#70]
Wir brauchen einen kleinen Text, um Dank und Credit zu geben.

Für unsere Korrekturleserin und ich würde sogar vorschlagen DeepL zu erwähnen.

Könnten wir im draft unten anbringen vor oder nach den notes.

**Comment by florianthiery** [comment]
Jups beides wäre wunderbar. Und vllt auch Lutz.
