### ISSUE TITLE
Greetings github action

### ISSUE THREAD

**Issue by nevrome** [Research-Squirrel-Engineers/DGUF_Leitfaden#72]
@ennatmm You enabled a Github Action to moderate this issue forum (https://github.com/Research-Squirrel-Engineers/Impuls_SoftwareRezensionen_DGUF/blob/master/.github/workflows/greetings.yml), but apparently you forgot to configure it then.

If you really want to have this, then we should replace "Message that will be displayed on users'' first issue" with something actually useful :smile:. Or maybe we deactivate the Action.

**Comment by nevrome** [comment]
:point_up_2: this

**Comment by HubertMara** [comment]
I'd vote for deactivate as I don't see any point in that message.

**Comment by bellerophons-pegasus** [comment]
But it might be helpful for people reacting to our article. 

I also replied to our first issue from external side with a short text explaining, that we won't immediately change the text.

> Vielen Dank!
> Da wir schon im early view veröffentlicht wurden, wird der Text jetzt noch nicht direkt weiter angepasst. Sobald aber ausreichend Input da ist, ist ein Folgeartikel sicher vorstellbar.
