### ISSUE TITLE
Text für welcome-bot formulieren

### ISSUE THREAD

**Issue by bellerophons-pegasus** [Research-Squirrel-Engineers/DGUF_Leitfaden#78]
Jeder, der zum ersten Mal ein Issue bei uns anlegt, bekommt von dem welcome-bot eine Nachricht. 

Inhalte
* Danke
* Gruppe
* Zeithorizont

**Comment by archaeoklammt** [comment]
**Vielen Dank für das Issue !** Wir freuen uns über das aktive Interesse an unserem Text, mit dem wir hoffen zur besseren wissenschaftlichen Wahrnehmung und angemessenen Diskussion von Forschungssoftware beitragen zu können.

Bitte haben Sie aber etwas Geduld. Als Team mit sieben Autor:innen benötigen wir einige Zeit, bis wir das Issue aufgreifen und reagieren. Dies kann ganz in Abhängigkeit der verschiedenen Verpflichtungen etwa 4 Wochen dauern.

**Thank you for the issue !** We appreciate your active interest in our text, with which we hope to contribute to a better scientific perception and appropriate discussion of research software.

However, please be patient. As a team of seven authors, we need some time to pick up and respond to the Issue. This may take about 4 weeks, depending on the various commitments.

**Comment by HubertMara** [comment]
Gefällt mir sehr gut, hat damit meine Zustimmung.

**Comment by situx** [comment]
Ich finde es auch ok, aber wir können im Welcome Bot nur eine Nachricht einstellen und nicht nach Sprachen unterscheiden. Würde daher das englische nehmen

**Comment by archaeoklammt** [comment]
Ich dachte eigentlich, dass der Bot es so ausspuckt, oben deutsch unten englisch (oder umgedreht).

**Comment by situx** [comment]
Auch das wäre möglich

**Comment by HubertMara** [comment]
Ist auf jeden Fall nicht umgesetzt - siehe das Issue von Timo vor einer Stunde.

**Comment by situx** [comment]
Wenn der Text final ist kann ich es umsetzen

**Comment by archaeoklammt** [comment]
@situx Denke, er ist fest. Also bitte gerne umsetzen. Merci

**Comment by situx** [comment]
Umgesetzt
